[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D -e -o ListenAddress=127.0.0.1 -o PasswordAuthentication=yes -o PermitRootLogin=no -o AllowUsers=pi -o UsePAM=no
priority=10
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:cockpit]
command=/usr/libexec/cockpit-ws --for-tls-proxy --local-ssh --port=9090
user=pi
environment=HOME="/home/pi",USER="pi"
directory=/home/pi
priority=20
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
